const categories = {
  Any: 0,
  "General Knowledge": 9,
  "Entertainment: Books": 10,
  "Entertainment: Film": 11,
  "Entertainment: Music": 12,
  "Musicals and Theatres": 13,
  Television: 14,
  "Video Games": 15,
  "Board Games": 16,
  "Science and Nature": 17,
  "Science: Computers": 18,
  "Science: Mathematics": 19,
  "Science: Gadgets": 30,
  Mythology: 20,
  Sports: 21,
  Geography: 22,
  History: 23,
  Politics: 24,
  Arts: 25,
  Celebrities: 26,
  Animals: 27,
  Vehicles: 28,
  "Comics": 29,
};

export default categories;
